import { useState, useCallback, useEffect, useRef } from 'react'
import { useLocation } from 'react-router-dom'
import { SetupForm } from '@/components/interview/SetupForm'
import { InterviewSidebar } from '@/components/interview/InterviewSidebar'
import { ChatBox } from '@/components/interview/ChatBox'
import { XpToast } from '@/components/interview/XpToast'
import { Badge } from '@/components/ui'
import { useConsistencyMetrics } from '@/contexts/ConsistencyMetricsContext'
import { useInterviewChat } from '@/hooks/useInterviewChat'
import { useInterviewQuestions } from '@/hooks/useInterviewQuestions'
import { supabase } from '@/lib/supabase'
import type { CompanyProfile, InterviewStyle, InterviewSessionSummary, ResumeSummary } from '@/types'
import { formatMinutes } from '@/utils/formatMinutes'
import styles from './InterviewPage.module.css'

type Phase = 'setup' | 'interview'

const SESSION_STORAGE_KEY = 'interview_active_session'

interface PersistedSession {
  sessionId: string | null
  companyName: string
  jobDescription: string
  style: InterviewStyle
  sidebarWidth?: number
  questionCooldownEnd?: number
}

function saveSession(data: PersistedSession): void {
  sessionStorage.setItem(SESSION_STORAGE_KEY, JSON.stringify(data))
}

function loadSession(): PersistedSession | null {
  const raw = sessionStorage.getItem(SESSION_STORAGE_KEY)
  if (!raw) return null
  try {
    return JSON.parse(raw) as PersistedSession
  } catch {
    return null
  }
}

function clearSession(): void {
  sessionStorage.removeItem(SESSION_STORAGE_KEY)
}

function getInitialState() {
  const saved = loadSession()
  if (!saved) return null
  return saved
}

export default function InterviewPage(): JSX.Element {
  const location = useLocation()
  const roleState = location.state as {
    companyName?: string
    companyProfileId?: string
    roleId?: string
    roleTitle?: string
    jobDescription?: string
  } | null

  const initialState = useRef(getInitialState())
  const { data: consistencyMetrics } = useConsistencyMetrics()
  const [phase, setPhase] = useState<Phase>(initialState.current ? 'interview' : 'setup')
  const [jobDescription, setJobDescription] = useState(
    roleState?.jobDescription || initialState.current?.jobDescription || ''
  )
  const [companyName, setCompanyName] = useState(
    roleState?.companyName || initialState.current?.companyName || ''
  )
  const [selectedCompanyId, setSelectedCompanyId] = useState<string | null>(
    roleState?.companyProfileId || null
  )
  const [companyRoleId, setCompanyRoleId] = useState<string | null>(roleState?.roleId || null)
  const [companyProfile, setCompanyProfile] = useState<CompanyProfile | null>(null)
  const [style, setStyle] = useState<InterviewStyle | null>(initialState.current?.style ?? 'mixed')
  const [selectedResumeId, setSelectedResumeId] = useState<string | null>(null)
  const [activeResume, setActiveResume] = useState<ResumeSummary | null>(null)

  const [activeSessionId, setActiveSessionId] = useState<string | null>(
    initialState.current?.sessionId ?? null,
  )

  const savedCooldown = initialState.current?.questionCooldownEnd ?? null
  const [questionCooldownEnd, setQuestionCooldownEnd] = useState<number | null>(
    savedCooldown && savedCooldown > Date.now() ? savedCooldown : null,
  )

  const handleCooldownStart = useCallback((end: number) => {
    setQuestionCooldownEnd(end)
    const saved = loadSession()
    if (saved) saveSession({ ...saved, questionCooldownEnd: end })
  }, [])

  const {
    questions,
    isGenerating,
    generateQuestions,
    toggleBookmark,
    updateNotes,
  } = useInterviewQuestions(activeSessionId, companyName)

  // XP toast state
  const [xpToasts, setXpToasts] = useState<Array<{ id: number; xp: number; label: string }>>([])

  const handleXpAwarded = useCallback((xp: number, eventType: string) => {
    const label = eventType === 'interview_start' ? 'Session Started!'
      : eventType === 'interview_milestone_5' ? '5-Message Milestone!'
      : eventType === 'interview_milestone_10' ? '10-Message Milestone!'
      : ''
    setXpToasts(prev => [...prev, { id: Date.now() + Math.random(), xp, label }])
  }, [])

  const { messages, isTyping, sendMessage, interviewSessionId, resumeSession, resetSession } =
    useInterviewChat(
      { jobDescription, companyName, companyContext: '' },
      style ?? 'mixed',
      activeResume,
      handleXpAwarded,
      companyRoleId,
    )

  // Keep activeSessionId in sync and persist to sessionStorage
  if (interviewSessionId !== activeSessionId) {
    setActiveSessionId(interviewSessionId)
    if (interviewSessionId) {
      saveSession({
        sessionId: interviewSessionId,
        companyName,
        jobDescription,
        style: style ?? 'mixed',
      })
    }
  }

  // Auto-generate questions when a new session is created
  const autoGeneratedForRef = useRef<string | null>(null)
  useEffect(() => {
    if (
      interviewSessionId &&
      interviewSessionId !== autoGeneratedForRef.current &&
      jobDescription.trim().length > 0 &&
      companyName.trim().length > 0
    ) {
      autoGeneratedForRef.current = interviewSessionId
      generateQuestions(
        jobDescription,
        companyName,
        style ?? 'mixed',
        interviewSessionId,
        selectedCompanyId,
      )
    }
  }, [interviewSessionId, jobDescription, companyName, style, selectedCompanyId, generateQuestions])

  // If there's a saved DB session, load its messages on mount
  const restoredRef = useRef(false)
  useEffect(() => {
    if (restoredRef.current) return
    restoredRef.current = true

    const saved = initialState.current
    if (!saved?.sessionId) return

    Promise.resolve(
      supabase
        .from('interview_sessions')
        .select('id, messages, job_description, interview_style, company_name')
        .eq('id', saved.sessionId)
        .single()
    )
      .then(({ data, error }) => {
        if (error || !data) return

        const loaded = (data.messages as Array<{ role: string; content: string; timestamp: string }>)
          .map((m, i) => ({
            id: `past-${i}`,
            role: m.role as 'user' | 'assistant',
            content: m.content,
            timestamp: new Date(m.timestamp),
          }))

        autoGeneratedForRef.current = data.id as string
        resumeSession(data.id as string, loaded)
      })
      .catch(() => {
        // Ignore — interview screen already showing with setup data
      })
  }, [resumeSession])

  function handleCompanyProfileSelect(profile: CompanyProfile): void {
    setCompanyName(profile.companyName)
    setSelectedCompanyId(profile.id)
    setCompanyProfile(profile)
  }

  function handleCompanyNameChange(value: string): void {
    setCompanyName(value)
    setSelectedCompanyId(null)
    setCompanyProfile(null)
  }

  function handleStart(resumeObject?: ResumeSummary | null): void {
    if (resumeObject) {
      setActiveResume(resumeObject)
    }

    saveSession({
      sessionId: null,
      companyName,
      jobDescription,
      style: style ?? 'mixed',
    })

    setPhase('interview')
  }

  function handleBack(): void {
    resetSession()
    autoGeneratedForRef.current = null
    setJobDescription('')
    setCompanyName('')
    setSelectedCompanyId(null)
    setCompanyRoleId(null)
    setCompanyProfile(null)
    setStyle('mixed')
    setActiveResume(null)
    clearSession()
    setPhase('setup')
  }

  const handleLoadSession = useCallback(async (session: InterviewSessionSummary) => {
    const { data, error } = await supabase
      .from('interview_sessions')
      .select('messages, job_description, interview_style, company_name, resume_id')
      .eq('id', session.id)
      .single()

    if (error || !data) {
      console.error('Failed to load interview session:', error)
      return
    }

    const loaded = (data.messages as Array<{ role: string; content: string; timestamp: string }>)
      .map((m, i) => ({
        id: `past-${i}`,
        role: m.role as 'user' | 'assistant',
        content: m.content,
        timestamp: new Date(m.timestamp),
      }))

    autoGeneratedForRef.current = session.id
    resumeSession(session.id, loaded)
    setCompanyName(data.company_name as string)
    if (data.job_description) setJobDescription(data.job_description as string)
    if (data.interview_style) setStyle(data.interview_style as InterviewStyle)

    if (data.resume_id) {
      const { data: resumeData } = await supabase
        .from('resumes')
        .select('id, title, is_primary, updated_at, structured_content, source_file_path')
        .eq('id', data.resume_id)
        .single()

      if (resumeData) {
        setActiveResume(resumeData)
        setSelectedResumeId(resumeData.id)
      }
    } else {
      // Ensure it's cleared if this past session didn't use a resume
      setActiveResume(null)
      setSelectedResumeId(null)
    }

    saveSession({
      sessionId: session.id,
      companyName: data.company_name as string,
      jobDescription: (data.job_description as string) ?? '',
      style: (data.interview_style as InterviewStyle) ?? 'mixed',
    })
    setPhase('interview')
  }, [resumeSession])

  const handleGenerateQuestions = useCallback(() => {
    generateQuestions(
      jobDescription,
      companyName,
      style ?? 'mixed',
      interviewSessionId,
      selectedCompanyId,
    )
  }, [generateQuestions, jobDescription, companyName, style, interviewSessionId, selectedCompanyId])

  const [sidebarWidth, setSidebarWidth] = useState(initialState.current?.sidebarWidth ?? 340)
  const isDragging = useRef(false)
  const todayMinutes = consistencyMetrics?.interview.dailyMinutes[6]?.minutes ?? 0

  const handleMouseDown = useCallback((e: React.MouseEvent) => {
    e.preventDefault()
    isDragging.current = true
    document.body.style.cursor = 'col-resize'
    document.body.style.userSelect = 'none'

    const onMouseMove = (ev: MouseEvent) => {
      if (!isDragging.current) return
      const newWidth = Math.min(Math.max(ev.clientX, 240), 600)
      setSidebarWidth(newWidth)
    }

    const onMouseUp = (ev: MouseEvent) => {
      isDragging.current = false
      document.body.style.cursor = ''
      document.body.style.userSelect = ''
      document.removeEventListener('mousemove', onMouseMove)
      document.removeEventListener('mouseup', onMouseUp)
      const finalWidth = Math.min(Math.max(ev.clientX, 240), 600)
      const saved = loadSession()
      if (saved) {
        saveSession({ ...saved, sidebarWidth: finalWidth })
      }
    }

    document.addEventListener('mousemove', onMouseMove)
    document.addEventListener('mouseup', onMouseUp)
  }, [])

  return (
    <>
      {phase === 'setup' ? (
        <div className={styles.setupPage}>
          <div className={styles.setupHeader}>
            <h1 className={styles.title}>Interview Simulator</h1>
            <p className={styles.subtitle}>
              Practice answering questions live with AI. Provide context to make it realistic.
            </p>
          </div>
          <SetupForm
            companyName={companyName}
            onCompanyNameChange={handleCompanyNameChange}
            selectedCompanyId={selectedCompanyId}
            onCompanyProfileSelect={handleCompanyProfileSelect}
            jobDescription={jobDescription}
            onJobDescriptionChange={setJobDescription}
            style={style}
            onStyleChange={setStyle}
            onStart={handleStart}
            onLoadSession={handleLoadSession}
            selectedResumeId={selectedResumeId}
            onResumeSelect={setSelectedResumeId}
          />
        </div>
      ) : (
        <div
          className={styles.interviewPage}
          style={{ gridTemplateColumns: `${sidebarWidth}px 6px 1fr` }}
        >
          <InterviewSidebar
            companyName={companyName}
            onCompanyNameChange={handleCompanyNameChange}
            selectedCompanyId={selectedCompanyId}
            companyProfile={companyProfile}
            onCompanyProfileSelect={handleCompanyProfileSelect}

            style={style ?? 'mixed'}
            jobDescription={jobDescription}
            onJobDescriptionChange={setJobDescription}
            questions={questions}
            isGenerating={isGenerating}
            onGenerateQuestions={handleGenerateQuestions}
            onToggleBookmark={toggleBookmark}
            onUpdateNotes={updateNotes}
            canGenerate={jobDescription.trim().length > 0 && companyName.trim().length > 0}
            onBack={handleBack}
            resume={activeResume}
            cooldownEnd={questionCooldownEnd}
            onCooldownStart={handleCooldownStart}
            companyRoleId={companyRoleId}
            roleTitle={roleState?.roleTitle || null}
          />
          <div className={styles.resizeHandle} onMouseDown={handleMouseDown} />
          <div className={styles.chatPanel}>
            <ChatBox
              messages={messages}
              isTyping={isTyping}
              onSend={sendMessage}
              disabled={false}
            />
            {xpToasts.map((t) => (
              <XpToast
                key={t.id}
                xp={t.xp}
                label={t.label}
                onDone={() => setXpToasts((prev) => prev.filter((x) => x.id !== t.id))}
              />
            ))}
          </div>
        </div>
      )}
    </>
  )
}
