import { useState, useCallback, useEffect, useRef } from 'react'
import { SetupForm } from '@/components/interview/SetupForm'
import { InterviewSidebar } from '@/components/interview/InterviewSidebar'
import { ChatBox } from '@/components/interview/ChatBox'
import { useInterviewChat } from '@/hooks/useInterviewChat'
import { useInterviewQuestions } from '@/hooks/useInterviewQuestions'
import { supabase } from '@/lib/supabase'
import type { CompanyProfile, InterviewStyle, InterviewSessionSummary } from '@/types'
import styles from './InterviewPage.module.css'

type Phase = 'setup' | 'interview'

export default function InterviewPage(): JSX.Element {
  const [phase, setPhase] = useState<Phase>('setup')
  const [jobDescription, setJobDescription] = useState('')
  const [companyName, setCompanyName] = useState('')
  const [selectedCompanyId, setSelectedCompanyId] = useState<string | null>(null)
  const [companyProfile, setCompanyProfile] = useState<CompanyProfile | null>(null)
  const [style, setStyle] = useState<InterviewStyle | null>('mixed')
  const [selectedResumeId, setSelectedResumeId] = useState<string | null>(null)
  const [activeResume, setActiveResume] = useState<any | null>(null)

  const [activeSessionId, setActiveSessionId] = useState<string | null>(null)

  const {
    questions,
    isGenerating,
    generateQuestions,
    toggleBookmark,
    updateNotes,
  } = useInterviewQuestions(activeSessionId)

  const { messages, isTyping, sendMessage, interviewSessionId, resumeSession, resetSession } =
    useInterviewChat(
      { jobDescription, companyName, companyContext: '' },
      style ?? 'mixed',
      activeResume,
    )

  // Keep activeSessionId in sync
  if (interviewSessionId !== activeSessionId) {
    setActiveSessionId(interviewSessionId)
  }

  // Auto-generate questions when a new session is created
  const autoGeneratedForRef = useRef<string | null>(null)
  useEffect(() => {
    if (
      interviewSessionId &&
      interviewSessionId !== autoGeneratedForRef.current &&
      jobDescription.trim().length > 0 &&
      companyName.trim().length > 0
    ) {
      autoGeneratedForRef.current = interviewSessionId
      generateQuestions(
        jobDescription,
        companyName,
        style ?? 'mixed',
        interviewSessionId,
        selectedCompanyId,
      )
    }
  }, [interviewSessionId, jobDescription, companyName, style, selectedCompanyId, generateQuestions])

  function handleCompanyProfileSelect(profile: CompanyProfile): void {
    setCompanyName(profile.companyName)
    setSelectedCompanyId(profile.id)
    setCompanyProfile(profile)
  }

  function handleCompanyNameChange(value: string): void {
    setCompanyName(value)
    setSelectedCompanyId(null)
    setCompanyProfile(null)
  }

  function handleStart(resumeObject?: any): void {
    if (resumeObject) {
      setActiveResume(resumeObject)
    }
    setPhase('interview')
  }

  function handleBack(): void {
    resetSession()
    autoGeneratedForRef.current = null
    setJobDescription('')
    setCompanyName('')
    setSelectedCompanyId(null)
    setCompanyProfile(null)
    setStyle('mixed')
    setActiveResume(null)
    setPhase('setup')
  }

  const handleLoadSession = useCallback(async (session: InterviewSessionSummary) => {
    const { data, error } = await supabase
      .from('interview_sessions')
      .select('messages, job_description, interview_style, company_name')
      .eq('id', session.id)
      .single()

    if (error || !data) {
      console.error('Failed to load interview session:', error)
      return
    }

    const loaded = (data.messages as Array<{ role: string; content: string; timestamp: string }>)
      .map((m, i) => ({
        id: `past-${i}`,
        role: m.role as 'user' | 'assistant',
        content: m.content,
        timestamp: new Date(m.timestamp),
      }))

    autoGeneratedForRef.current = session.id
    resumeSession(session.id, loaded)
    setCompanyName(data.company_name as string)
    if (data.job_description) setJobDescription(data.job_description as string)
    if (data.interview_style) setStyle(data.interview_style as InterviewStyle)
    setPhase('interview')
  }, [resumeSession])

  const handleGenerateQuestions = useCallback(() => {
    generateQuestions(
      jobDescription,
      companyName,
      style ?? 'mixed',
      interviewSessionId,
      selectedCompanyId,
    )
  }, [generateQuestions, jobDescription, companyName, style, interviewSessionId, selectedCompanyId])

  if (phase === 'setup') {
    return (
      <div className={styles.setupPage}>
        <div className={styles.setupHeader}>
          <h1 className={styles.title}>Interview Simulator</h1>
          <p className={styles.subtitle}>
            Practice answering questions live with AI. Provide context to make it realistic.
          </p>
        </div>
        <SetupForm
          companyName={companyName}
          onCompanyNameChange={handleCompanyNameChange}
          selectedCompanyId={selectedCompanyId}
          onCompanyProfileSelect={handleCompanyProfileSelect}
          jobDescription={jobDescription}
          onJobDescriptionChange={setJobDescription}
          style={style}
          onStyleChange={setStyle}
          onStart={handleStart}
          onLoadSession={handleLoadSession}
          selectedResumeId={selectedResumeId}
          onResumeSelect={setSelectedResumeId}
        />
      </div>
    )
  }

return (
    <div className={styles.interviewPage}>
      <InterviewSidebar
        companyName={companyName}
        onCompanyNameChange={handleCompanyNameChange}
        selectedCompanyId={selectedCompanyId}
        companyProfile={companyProfile}
        onCompanyProfileSelect={handleCompanyProfileSelect}

        style={style ?? 'mixed'}
        jobDescription={jobDescription}
        onJobDescriptionChange={setJobDescription}
        questions={questions}
        isGenerating={isGenerating}
        onGenerateQuestions={handleGenerateQuestions}
        onToggleBookmark={toggleBookmark}
        onUpdateNotes={updateNotes}
        canGenerate={jobDescription.trim().length > 0 && companyName.trim().length > 0}
        onBack={handleBack}
        resume={activeResume}
      />
      <div className={styles.chatPanel}>
        <ChatBox
          messages={messages}
          isTyping={isTyping}
          onSend={sendMessage}
          disabled={false}
        />
      </div>
    </div>
  )
}
